#version: '3.8'
#
#services:
#  postgres:
#    image: postgres
#    container_name: postgres_container
#    environment:
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: root2545
#    volumes:
#      - type: bind
#        source: C:/DataDocker:/var/lib/postgresql/data
#        target: /var/lib/postgresql/data
#        read_only: false
#        consistency: consistent
#    ports:
#      - "5432:5432"